### ISSUE TITLE
Failed to parse URL from /api/auth/csrf

### ISSUE THREAD

**Issue by ericwaetke** [OrJDev/solid-auth#7]
Hi,

so I get this error every time I load the page.

```
An unhandled error occured: TypeError: Failed to parse URL from /api/auth/csrf
    at fetch (...\node_modules\.pnpm\undici@5.20.0\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.signIn (.../node_modules/.pnpm/@solid-auth+base@2.0.3_@auth+core@0.5.1_solid-js@1.7.5_solid-start@0.2.26/node_modules/@solid-auth/base/client.js:137:29)
```

On the dev server, this doesnt do anything. Everything, still works fine. Login, Logout, everything fine. But it crashes the app in production. I tried to look into what causes that, but I don't think I'm skilled enough for that. None of the console.logs in the client.js file actually print something in the console.

I only have credential auth with a custom login page.

Do I have something misconfigured?

Edit: I can also post more code snippets, but I don't know if they are necessary for this problem and I didn't want to bloat the issue.

**Comment by ericwaetke** [comment]
Alright. Looks like i figured it out.

As this is my first real Solid project, I'm not 100% sure if this is what happened.

I had an automatic redirect, which called the `signIn` function when the session didn't exist. This code must've run on the server, and not just on the client, which is why the fetch request failed.

I'm now more conscious about client and server rendering and will probably need to learn more about how solid and solid start deal with that in the future.
